### ISSUE TITLE
Enhancement: Ausgänge der Räume sollten strandartmäßig auf False anstatt auf True

### ISSUE THREAD

**Issue by LukasKlein00** [LukasKlein00/SWEProjekt2021#67]
Van Hoof sagte mal dass es besser sein würde wenn man das so macht, weil der Spieler sich dann aktiv dazu entscheiden würde das so zu machen statt davon auszugehen dass man da durch soll

**Comment by Weofi** [comment]
ist umgesetzt, find ich aber blöd ^^
